#!/usr/bin/env python3
from pathlib import Path
import re
import json
import subprocess
from collections import defaultdict

ROOT = Path.cwd()
REPORT = ROOT / "STUDYBUDDY_REPO_AUDIT_REPORT.md"

def run(cmd):
    try:
        return subprocess.check_output(cmd, cwd=ROOT, stderr=subprocess.STDOUT, text=True, timeout=25)
    except Exception as e:
        return f"[FAILED] {' '.join(cmd)}\n{e}\n"

def find_files():
    ignore = {"vendor", "node_modules", ".git", "storage", "bootstrap/cache"}
    files = []
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        if any(part in ignore for part in p.parts):
            continue
        if p.suffix in [".php", ".blade.php", ".css", ".js", ".json", ".md", ".env", ".example"]:
            files.append(p)
    return files

def grep(pattern, files):
    rx = re.compile(pattern)
    hits = []
    for p in files:
        try:
            text = p.read_text(errors="ignore")
        except Exception:
            continue
        for i, line in enumerate(text.splitlines(), 1):
            if rx.search(line):
                hits.append((p.relative_to(ROOT), i, line.strip()[:220]))
    return hits

def route_names_from_code(files):
    names = []
    rx = re.compile(r"route\(\s*['\"]([^'\"]+)['\"]")
    for p in files:
        if p.suffix not in [".php", ".blade.php"]:
            continue
        text = p.read_text(errors="ignore")
        for match in rx.finditer(text):
            names.append((match.group(1), p.relative_to(ROOT)))
    return names

def asset_paths_from_code(files):
    paths = []
    patterns = [
        re.compile(r"asset\(\s*['\"]([^'\"]+)['\"]"),
        re.compile(r"['\"](assets/[^'\"]+\.(?:png|jpg|jpeg|svg|webp))['\"]"),
    ]
    for p in files:
        text = p.read_text(errors="ignore")
        for rx in patterns:
            for match in rx.finditer(text):
                paths.append((match.group(1), p.relative_to(ROOT)))
    return paths

files = find_files()

route_list = run(["php", "artisan", "route:list"])
missing_route_mentions = []
routes_defined = set()
for line in route_list.splitlines():
    # route list usually contains a route name column; keep simple robust scan
    for token in re.findall(r"[a-zA-Z0-9_.-]+\.[a-zA-Z0-9_.-]+", line):
        routes_defined.add(token)

for name, where in route_names_from_code(files):
    if name not in routes_defined and not name.startswith(("password.", "verification.", "login", "logout", "register")):
        missing_route_mentions.append((name, where))

assets = asset_paths_from_code(files)
missing_assets = []
for path, where in assets:
    clean = path.split("?")[0].lstrip("/")
    if clean.startswith("http"):
        continue
    if not (ROOT / "public" / clean).exists():
        missing_assets.append((path, where))

junk = []
for pattern in ["studybuddy_*_patch", "studybuddy_*_patch.zip", "_*_backup_*", "*.bak", "*.orig"]:
    junk.extend([p.relative_to(ROOT) for p in ROOT.glob(pattern)])

placeholders = grep(r"TODO|FIXME|Lorem|placeholder|dummy|sample text|coming soon|No social links added yet|Untitled|random", files)
old_routes = grep(r"pages\.apps|studybuddy\.experience\.|app-ecosystem|app-launchpad", files)
admin_outside = grep(r"/admin/studybuddy|/admin/site-settings|/admin/dashboard", files)

php_syntax = []
for p in [f for f in files if f.suffix == ".php"]:
    out = run(["php", "-l", str(p)])
    if "No syntax errors detected" not in out:
        php_syntax.append((p.relative_to(ROOT), out.strip()))

content = []
content.append("# StudyBuddy Repo Audit Report\n")
content.append("Generated by `audit_studybuddy_project.py`.\n")
content.append("## Route list check\n")
content.append("```text\n" + route_list[:6000] + ("\n...trimmed..." if len(route_list) > 6000 else "") + "\n```\n")

content.append("## Missing route() references found in code\n")
if missing_route_mentions:
    for name, where in sorted(set(missing_route_mentions)):
        content.append(f"- `{name}` in `{where}`")
else:
    content.append("- None found from static scan.")

content.append("\n## Missing asset/image paths\n")
if missing_assets:
    for path, where in sorted(set(missing_assets))[:200]:
        content.append(f"- `{path}` referenced in `{where}`")
else:
    content.append("- None found from static scan.")

content.append("\n## Placeholder / unfinished content hits\n")
if placeholders:
    for p, line, txt in placeholders[:250]:
        content.append(f"- `{p}:{line}` — {txt}")
else:
    content.append("- None found.")

content.append("\n## Old route/page names still mentioned\n")
if old_routes:
    for p, line, txt in old_routes[:250]:
        content.append(f"- `{p}:{line}` — {txt}")
else:
    content.append("- None found.")

content.append("\n## Admin links outside /admin/control-room\n")
if admin_outside:
    for p, line, txt in admin_outside[:250]:
        content.append(f"- `{p}:{line}` — {txt}")
else:
    content.append("- None found.")

content.append("\n## Junk patch/backup files in project root\n")
if junk:
    for item in junk:
        content.append(f"- `{item}`")
else:
    content.append("- None found.")

content.append("\n## PHP syntax issues\n")
if php_syntax:
    for p, out in php_syntax:
        content.append(f"### `{p}`\n```text\n{out}\n```")
else:
    content.append("- None found by `php -l`.")

REPORT.write_text("\n".join(content), encoding="utf-8")
print(f"Audit complete: {REPORT}")
