
<?php $__env->startSection('content'); ?>
<?php $__currentLoopData = $sections; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $section): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<section id="<?php echo e($section->section_key); ?>" class="home-section section-<?php echo e($section->section_type); ?>" <?php if($section->background_image_path): ?> style="background-image:linear-gradient(135deg, rgba(13,10,40,.86), rgba(31,50,124,.7)), url('<?php echo e(asset($section->background_image_path)); ?>')" <?php endif; ?>>
  <div class="section-copy"><p class="eyebrow"><?php echo e($section->eyebrow); ?></p><h1><?php echo e($section->title); ?></h1><p class="subtitle"><?php echo e($section->subtitle); ?></p><p><?php echo e($section->body); ?></p><div class="actions"><?php if($section->button_label): ?><a class="btn primary" href="<?php echo e($section->button_url ?: '#top'); ?>"><?php echo e($section->button_label); ?></a><?php endif; ?> <?php if($section->secondary_button_label): ?><a class="btn ghost" href="<?php echo e($section->secondary_button_url ?: '#footer'); ?>"><?php echo e($section->secondary_button_label); ?></a><?php endif; ?></div></div>
  <?php if($section->image_path): ?><img class="section-art" src="<?php echo e(asset($section->image_path)); ?>" alt="<?php echo e($section->title); ?>"><?php endif; ?>
  <?php if($section->items->isNotEmpty()): ?><div class="card-grid"><?php $__currentLoopData = $section->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="glow-card"><?php if($item->badge_text): ?><span><?php echo e($item->badge_text); ?></span><?php endif; ?> <?php if($item->image_path): ?><img src="<?php echo e(asset($item->image_path)); ?>" alt="<?php echo e($item->title); ?>"><?php endif; ?><h3><?php echo e($item->title); ?></h3><p><?php echo e($item->subtitle); ?></p><p><?php echo e($item->body); ?></p><?php if($item->button_label): ?><a href="<?php echo e($item->button_url ?: '#top'); ?>"><?php echo e($item->button_label); ?></a><?php endif; ?></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?>
</section>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\My real data\Biz\PixelCraftsLab\Projects\Study Buddy\website\StudyBuddy\resources\views/home.blade.php ENDPATH**/ ?>