<?php
namespace App\Models;
use Carbon\Carbon;use Illuminate\Contracts\Auth\MustVerifyEmail;use Illuminate\Database\Eloquent\Factories\HasFactory;use Illuminate\Database\Eloquent\Relations\HasMany;use Illuminate\Foundation\Auth\User as Authenticatable;use Illuminate\Notifications\Notifiable;
class User extends Authenticatable implements MustVerifyEmail{
 use HasFactory,Notifiable;
 protected $fillable=['name','real_name','email','password','role','avatar_style','learning_stage','cosmic_points','is_admin','date_of_birth','country','guardian_email','organization_name','organization_email','position_title','role_verification_status','role_verification_notes','age_verified_at','role_verified_at','safeguarding_agreed_at','verification_submitted_at','adult_verification_status','adult_verification_method','adult_verification_reference','adult_verification_consent_at','adult_verification_submitted_at','adult_verification_reviewed_at'];
 protected $hidden=['password','remember_token'];
 protected function casts():array{return ['email_verified_at'=>'datetime','password'=>'hashed','cosmic_points'=>'integer','is_admin'=>'boolean','date_of_birth'=>'date','age_verified_at'=>'datetime','role_verified_at'=>'datetime','safeguarding_agreed_at'=>'datetime','verification_submitted_at'=>'datetime','adult_verification_consent_at'=>'datetime','adult_verification_submitted_at'=>'datetime','adult_verification_reviewed_at'=>'datetime'];}
 public function requestedConnections():HasMany{return $this->hasMany(AccountConnection::class,'requester_id');} public function receivedConnections():HasMany{return $this->hasMany(AccountConnection::class,'target_id');} public function verificationCases():HasMany{return $this->hasMany(StudyBuddyVerificationCase::class);} public function hasVerifiedRole():bool{return in_array($this->role_verification_status,['verified','not_required'],true);} public function isPowerRole():bool{return in_array($this->role,['parent','teacher','independent_learner','admin'],true);} public function isAdult():bool{return $this->date_of_birth?Carbon::parse($this->date_of_birth)->age>=18:false;} public function needsAdultVerification():bool{return in_array($this->role,['parent','teacher','independent_learner','admin'],true);} public function hasVerifiedAdultStatus():bool{return !$this->needsAdultVerification()||in_array($this->adult_verification_status,['verified','manual_verified'],true)||!empty($this->age_verified_at);} }
